version: '3'

services:
  avante-rag-service:
    build:
      context: /home/faiyt/codebase/avante.nvim/py/rag-service
      dockerfile: Dockerfile
    image: quay.io/yetoneful/avante-rag-service:0.0.10
    container_name: avante-rag-service
    platform: linux/amd64
    network_mode: host
    volumes:
      - ./data:/data
      - /home/faiyt/codebase:/host:ro
    environment:
      - ALLOW_RESET=TRUE
      - DATA_DIR=/data
      - RAG_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=https://api.openai.com/v1
      - RAG_LLM_MODEL=gpt-3.5-turbo
      - RAG_EMBED_MODEL=text-embedding-ada-002
    ports:
      - "20250:20250"
    # Enable this to keep container running for debugging
    # command: ["/bin/bash", "-c", "while true; do sleep 60; done"]

# For easier debugging, add these profiles
# profiles:
#   debug:
#     extends:
#       service: avante-rag-service
#     command: ["/bin/bash", "-c", "while true; do sleep 60; done"]
#     entrypoint: /bin/bash
